81: switch to Photon
Oxygen gives problem when running UI tests with Java 11:
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct

Task-Url: http://github.com/pitest/pitclipse/issues/81