Use Import-Package instead of Require-Bundle to depend on Guava
Because:
 - it can lead to the following runtime error:
     java.lang.LinkageError: loader constraint violation: loader
     (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader)
     previously initiated loading for a different type with name
 - Import-Package seems to fix the issue, even if I still don't fully
     understand why.